### ISSUE TITLE
Run query should format data as hex/base64

### ISSUE THREAD

**Issue by willclarktech** [CosmWasm/code-explorer#36]
Currently the result of running a query looks like this:
```
{
  "data": {
    "0": 123,
    "1": 34,
    "2": 97,
    "3": 109,
    "4": 111,
    "5": 117,
    "6": 110,
    "7": 116,
    "8": 34,
    // ...
  }
}
```

**Comment by webmaster128** [comment]
In which network/contract do you see this problem?

It works for http://localhost:3000/contracts/cosmos1r856krgwz2r98jmtzgerxe4scg8m93akp2ur7q via

```
yarn start-heldernet
```

<img width="592" alt="Bildschirmfoto 2020-12-20 um 21 50 58" src="https://user-images.githubusercontent.com/2603011/102724130-9fd36800-430d-11eb-8192-48540b11ef96.png">

**Comment by willclarktech** [comment]
- `yarn start-stargate`
- http://localhost:3000/contracts/wasm1vs2vuks65rq7xj78mwtvn7vvnm2gn7ad78g6yp
<img width="420" alt="Screenshot 2020-12-22 at 10 30 07" src="https://user-images.githubusercontent.com/11036220/102878818-1f198680-4449-11eb-9d4d-5bfc6bf6c976.png">

**Comment by willclarktech** [comment]
I mean, ideally the stargate queries would be decoded further, but this issue is about a general way of displaying binary data.

**Comment by webmaster128** [comment]
@willclarktech all CosmWasm contracts are designed to use the CosmWasm `Binary` type for binary data. This is base64 encoded when going through JSON.

So there is a decoding step missing in Stargate that exists in Launchpad. Could you create a CosmJS ticket for that?

**Comment by willclarktech** [comment]
@webmaster128 https://github.com/cosmos/cosmjs/issues/590

**Comment by webmaster128** [comment]
Fixed via CosmJS upgrade:

<img width="556" alt="Bildschirmfoto 2020-12-23 um 11 02 10" src="https://user-images.githubusercontent.com/2603011/102984754-57cf6380-450e-11eb-8457-fab9e65db99e.png">
