### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/code-explorer#39]
I wanted to try it out, two issues. The deployed app that is linked is very outdated. And the quick start command connects to devnet, which is bad for demos.

Actions:

- [x] Deploy newest version and update link in readme as needed.
- [x] Make start scripts more flexible https://github.com/CosmWasm/code-explorer/issues/39#issuecomment-749405337
- [x] Document quick start running it locally *against real testnets*, `yarn start-heldernet` should be prominent. You can keep the dev test (local chain), but then please link to how to start a local devnet (I think this is somewhere is CosmJS docs). Then someone can follow all the steps to view it fully locally for development.
- [ ] Re-deploy once this is feature-complete for ICF (Wed?)

Main goal is someone (me, ICF, other devs) being able to look at the repo and try it out and get an initial impression in 5-10 minutes. Then, if they want to dig into the code, they can, but the overview and understand what is going on should be quick and easy.

**Comment by webmaster128** [comment]
Let's create a `start-launchpad` start script for `REACT_APP_BACKEND=devnetLaunchpad` and convert `yarn start` to an alias to `yarn start-heldernet`. Then we have one explicit command per network and can switch the default `yarn start` easily over time.

**Comment by webmaster128** [comment]
Done
