### ISSUE TITLE
Contract execution messages are not displayed (Launchpad)

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/code-explorer#50]
Right now, contract execution messages are not displayed when connecting to Heldernet

1. `yarn && yarn start`
2. Open a contract, like http://localhost:3000/contracts/cosmos1w8efgymkdqafech2c0y40hgvxa23tmmgsmuz66. It shows a list of execution transactions
3. Click on details, like http://localhost:3000/transactions/54389D2D015A69B13B6DBC4C6D7667BDB758DEC429E112D3B506CB0B69437A08. The message type is missing

<img width="1189" alt="Bildschirmfoto 2020-12-22 um 16 49 30" src="https://user-images.githubusercontent.com/2603011/102906982-ac72d000-4475-11eb-904d-9c56b1e8094a.png">

**Comment by willclarktech** [comment]
See https://github.com/cosmos/cosmjs/issues/592
