### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by JakeHartnell** [CosmWasm/code-explorer#70]
Juno testnet has gotten so popular we need pagination: https://blueprints.juno.giansalex.dev/#/codes

**Comment by webmaster128** [comment]
The example there shows 89 entries. Did the network change since you opened the ticket? There seems to be a cap at 100 right now.

Are you referring to the UI or the network requests and access to more than 100 contracts?

**Comment by JakeHartnell** [comment]
> The example in your link shows 89 entries right now. Did the network change since you opened the ticket? There seems to be a cap at 100 right now that I see when connecting to Sandynet.
> 
> Are you referring to the UI or the network requests and access to more than 100 contracts?

Yes, the network has changed since I opened the ticket. Juno's Uni Testnet has been refreshed.
